### ISSUE TITLE
U4 and TWRP

### ISSUE THREAD

**Issue by codechara** [Galaxy-MT6768/android_device_samsung_a31nsxx#11]
(I do not know English, I use a translator)

Hi! I have a Samsung galaxy a31 with version 4 of the bootloader.
Stock and gsi work, the problem is that twrp cannot read (or open) any directories.

Here is the main part of the log:
`Updating partition details...
I:checking for twrp app
Error opening: '/data/bootchart' (Permission denied)
Error opening: '/data/vendor' (Permission denied)
Error opening: '/data/vendor_ce/0' (Permission denied)
Error opening: '/data/vendor_de/0' (Permission denied)
Error opening: '/data/anr' (Permission denied)
Error opening: '/data/tombstones' (Permission denied)
Error opening: '/data/misc' (Permission denied)
Error opening: '/data/property' (Permission denied)
Error opening: '/data/apex/decompressed' (Permission denied)
Error opening: '/data/apex/ota_reserved' (Permission denied)
Error opening: '/data/app-staging' (Permission denied)
Error opening: '/data/local' (Permission denied)
Error opening: '/data/data' (Permission denied)
Error opening: '/data/app-private' (Permission denied)
Error opening: '/data/app-ephemeral' (Permission denied)
Error opening: '/data/app-asec' (Permission denied)
Error opening: '/data/app-lib' (Permission denied)
Error opening: '/data/app' (Permission denied)
Error opening: '/data/fonts' (Permission denied)
Error opening: '/data/dalvik-cache' (Permission denied)
Error opening: '/data/ota' (Permission denied)
Error opening: '/data/ota_package' (Permission denied)
Error opening: '/data/resource-cache' (Permission denied)
Error opening: '/data/drm' (Permission denied)
Error opening: '/data/mediadrm' (Permission denied)
Error opening: '/data/nfc' (Permission denied)
Error opening: '/data/backup' (Permission denied)
Error opening: '/data/ss' (Permission denied)
Error opening: '/data/system' (Permission denied)
Error opening: '/data/system_de/0' (Permission denied)
Error opening: '/data/system_ce/0' (Permission denied)
Error opening: '/data/misc_de/0' (Permission denied)
Error opening: '/data/misc_ce/0' (Permission denied)
Error opening: '/data/user_de/0' (Permission denied)
Error opening: '/data/rollback' (Permission denied)
Error opening: '/data/rollback-observer' (Permission denied)
Error opening: '/data/rollback-history' (Permission denied)
Error opening: '/data/incremental' (Permission denied)
Error opening: '/data/bootanim' (Permission denied)
Error opening: '/data/adb' (Permission denied)
Error opening: '/data/adbroot' (Permission denied)
Error opening: '/data/lineageos_updates' (Permission denied)
Error opening: '/data/ssh' (Permission denied)
Error opening: '/data/server_configurable_flags' (Permission denied)`

The entire log is attached.
[recovery.log](https://github.com/Galaxy-MT6768/teamwin_device_samsung_a31/files/12861402/recovery.log)

**Comment by DevZillion** [comment]
Hey! It looks that you have missed to disable the file based encryption and format data.
Flashable zip to disable FBE: https://github.com/Galaxy-MT6768/tw_zips/raw/main/fbe_disabler.zip
