### ISSUE TITLE
why supply 0 (zero) to avbtool?

### ISSUE THREAD

**Issue by crazo7924** [Galaxy-MT6768/android_device_samsung_a31nsxx#5]
https://github.com/Galaxy-MT6768/android_device_samsung_a31nsxx/blob/d26e94d0c7cdb57619b1a654f892a797d88b724e/BoardConfig.mk#L107

You can sign the recovery but all other ones must be if you flash your own vbmeta image
> First you should checksum/sign all other partition images that are part of your AVB process (for example, boot, system, etc)!

Read the more about Android Verified Boot
https://wiki.postmarketos.org/wiki/Android_Verified_Boot_(AVB)

You can supply '3' as per this commit
https://review.lineageos.org/c/LineageOS/android_device_xiaomi_sm8250-common/+/314082/1

**Comment by DevZillion** [comment]
Hi, Didn't saw this on time. I was working on TWRP booting without the need of a custom vbmeta, thing that is already working.
I'll check your Issue and see what I can find, tysm.

**Comment by DevZillion** [comment]
Ok the flag 0 was set because the stock vbmeta.img will always have **--flag 0** to only allow signed images to run.
Hope you understand this and hope I'm not missing anything, if I'm missing anything tell me, if no tell me too so I can close the issue, thx for the issue anyways ;)

**Comment by DevZillion** [comment]
In this case flag 3 is useless as we are not building any custom rom, just a recovery.
Good way to close an issue lol
