### ISSUE TITLE
samsung a31(f) Android11 bootlooped after flash twrp

### ISSUE THREAD

**Issue by rezatavakkol1400** [Galaxy-MT6768/android_device_samsung_a31nsxx#8]
If your device is sm-a315f, hold on and read carefully

I have installed twrp version 3.6.2 many times with different methods and faced bootloop problem . I hope this problem will be solved soon 

If your phone is a31 and you want to install twrp, hold on and
1-Make a backup (if your phone is rooted without twrp, it is better to use Titanium Backup)
2-Have the firmware file (AP, BL, CP, CSC,HOME CSC) ready and flash it if needed, but all your data will be gone.
3-To exit the bootloop, extract the recovery.img file from the AP file and flash it with Odin (Also, if your device is rooted, you can backup your stock recovery from the twrp mobile application and flash it to solve the bootloop)

Good luck

**Comment by DevZillion** [comment]
Your issue is not flashing a disabled vbmeta + not using the latest Android Version.
For Android 11 you'll have to build twrp from my android-11 branch.

**Comment by omar-120** [comment]
> If your device is sm-a315f, hold on and read carefully
> 
> I have installed twrp version 3.6.2 many times with different methods and faced bootloop problem . I hope this problem will be solved soon
> 
> If your phone is a31 and you want to install twrp, hold on and 1-Make a backup (if your phone is rooted without twrp, it is better to use Titanium Backup) 2-Have the firmware file (AP, BL, CP, CSC,HOME CSC) ready and flash it if needed, but all your data will be gone. 3-To exit the bootloop, extract the recovery.img file from the AP file and flash it with Odin (Also, if your device is rooted, you can backup your stock recovery from the twrp mobile application and flash it to solve the bootloop)
> 
> Good luck

Could you please expand a little more i am new to this and it i think my phone is bootlooping but i dont undertstand the steps you gave e.g how do i extract recovery.img from AP file
Edit: I extracted the recovery.img file now i just need to know wether i should flash it in AP, BL, CP, CSC,HOME CSC also my phone is the A315G...would this still work?

**Comment by rezatavakkol1400** [comment]
> > If your device is sm-a315f, hold on and read carefully
> > I have installed twrp version 3.6.2 many times with different methods and faced bootloop problem . I hope this problem will be solved soon
> > If your phone is a31 and you want to install twrp, hold on and 1-Make a backup (if your phone is rooted without twrp, it is better to use Titanium Backup) 2-Have the firmware file (AP, BL, CP, CSC,HOME CSC) ready and flash it if needed, but all your data will be gone. 3-To exit the bootloop, extract the recovery.img file from the AP file and flash it with Odin (Also, if your device is rooted, you can backup your stock recovery from the twrp mobile application and flash it to solve the bootloop)
> > Good luck
> 
> Could you please expand a little more i am new to this and it i think my phone is bootlooping but i dont undertstand the steps you gave e.g how do i extract recovery.img from AP file Edit: I extracted the recovery.img file now i just need to know wether i should flash it in AP, BL, CP, CSC,HOME CSC also my phone is the A315G...would this still work?

With 7-zip . install that right click on ap file Select the add to archive... option And change the file extension to zip and extract like a normal "zip" file

**Comment by DevZillion** [comment]
> Could you please expand a little more i am new to this and it i think my phone is bootlooping but i dont undertstand the steps you gave e.g how do i extract recovery.img from AP file Edit: I extracted the recovery.img file now i just need to know wether i should flash it in AP, BL, CP, CSC,HOME CSC also my phone is the A315G...would this still work?

Just flash the .tar file into AP and hold volume up + power while the phone reboots to boot into TWRP.
